import type { AdminNavLink, AdminLookupLink } from '@/src/types/nav';

import { appIcons } from './app-icons';

export const adminLinks: readonly AdminNavLink[] = [
  {
    label: 'Πίνακας Ελέγχου',
    href: { pathname: '/' },
    icon: appIcons.dashboard,
    iconKey: 'dashboard',
    accessibility: 'Πίνακας Ελέγχου',
  },
  {
    label: 'Προσωπικό',
    href: { pathname: '/personnel' },
    icon: appIcons.personnel,
    iconKey: 'personnel',
    countKey: 'personnel',
    accessibility: 'Προσωπικό',
  },
  {
    label: 'Χώρες',
    href: { pathname: '/countries' },
    icon: appIcons.countries,
    iconKey: 'countries',
    countKey: 'countries',
    accessibility: 'Χώρες',
  },
  {
    label: 'Εξοπλισμοί',
    href: { pathname: '/equipments' },
    icon: appIcons.equipment,
    iconKey: 'equipments',
    countKey: 'equipments',
    accessibility: 'Εξοπλισμοί',
  },
  {
    label: 'Εταιρείες',
    href: { pathname: '/companies' },
    icon: appIcons.companies,
    iconKey: 'companies',
    countKey: 'companies',
    accessibility: 'Εταιρείες',
  },
  {
    label: 'Έγγραφα',
    href: { pathname: '/documents' },
    icon: appIcons.documents,
    iconKey: 'documents',
    countKey: 'documents',
    accessibility: 'Εταιρείες',
  },
  {
    label: 'Εργαλεία',
    href: { pathname: '/tools' },
    icon: appIcons.tools,
    iconKey: 'tools',
    countKey: 'tools',
    accessibility: 'Εργαλεία',
  },
] as const;

export const lookUpDataLinks: readonly AdminLookupLink[] = [
  {
    label: 'Διευθύνσεις',
    href: { pathname: '/tools/directorates' },
    icon: appIcons.directorates,
    iconKey: 'directorates',
    countKey: 'directorates',
    value: 'directorates',
    type: 'personnel',
  },
  {
    label: 'Τμήματα',
    href: { pathname: '/tools/departments' },
    icon: appIcons.departments,
    iconKey: 'departments',
    countKey: 'departments',
    value: 'departments',
    type: 'personnel',
  },
  {
    label: 'Τομείς',
    href: { pathname: '/tools/department-sectors' },
    icon: appIcons.sectors,
    iconKey: 'departmentSectors',
    countKey: 'departmentSectors',
    value: 'departmentSectors',
    type: 'personnel',
  },
  {
    label: 'Αρχηγεία',
    href: { pathname: '/tools/units', query: { type: 'hq' } },
    icon: appIcons.headQuarters,
    iconKey: 'headQuarters',
    countKey: 'headQuarters',
    value: 'headQuarters',
    type: 'personnel',
  },
  {
    label: 'Σχηματισμοί',
    href: {
      pathname: '/tools/units',
      query: { type: 'formation' },
    },
    icon: appIcons.formations,
    iconKey: 'formations',
    countKey: 'formations',
    value: 'formations',
    type: 'personnel',
  },
  {
    label: 'Υπο Μονάδες',
    href: { pathname: '/tools/units', query: { type: 'subunit' } },
    icon: appIcons.subUnits,
    iconKey: 'subUnits',
    countKey: 'subUnits',
    value: 'subUnits',
    type: 'personnel',
  },
  {
    label: 'Μονάδες',
    href: { pathname: '/tools/units', query: { type: 'unit' } },
    icon: appIcons.units,
    iconKey: 'units',
    countKey: 'units',
    value: 'units',
    type: 'personnel',
  },
  {
    label: 'Κλάδοι',
    href: { pathname: '/tools/branches' },
    icon: appIcons.branches,
    iconKey: 'branches',
    countKey: 'branches',
    value: 'branches',
    type: 'personnel',
  },
  {
    label: 'Καθήκοντα',
    href: { pathname: '/tools/positions' },
    icon: appIcons.positions,
    iconKey: 'positions',
    countKey: 'positions',
    value: 'positions',
    type: 'personnel',
  },
  {
    label: 'Τύποι',
    href: { pathname: '/tools/doc-types' },
    icon: appIcons.docTypes,
    iconKey: 'docTypes',
    countKey: 'docTypes',
    value: 'docTypes',
    type: 'documents',
  },
  {
    label: 'Κατηγορίες',
    href: { pathname: '/tools/doc-type-categories' },
    icon: appIcons.docTypeCategories,
    iconKey: 'docTypeCategories',
    countKey: 'docTypeCategories',
    value: 'docTypeCategories',
    type: 'documents',
  },
  {
    label: 'Χώρες',
    href: { pathname: '/tools/countries' },
    icon: appIcons.countries,
    iconKey: 'countries',
    countKey: 'countries',
    value: 'countries',
    type: 'application',
  },
  {
    label: 'Περιοχές',
    href: { pathname: '/tools/regions' },
    icon: appIcons.regions,
    iconKey: 'regions',
    countKey: 'regions',
    value: 'regions',
    type: 'application',
  },
  {
    label: 'Οργανισμοί',
    href: { pathname: '/tools/organizations' },
    icon: appIcons.organizations,
    iconKey: 'organizations',
    countKey: 'organizations',
    value: 'organizations',
    type: 'application',
  },
] as const;

export const navLinks: readonly AdminNavLink[] = [
  {
    href: { pathname: '/' },
    label: 'Πίνακας Ελέγχου',
    icon: appIcons.dashboard,
    iconKey: 'dashboard',
    accessibility: 'Πίνακας Ελέγχου',
  },
  {
    href: { pathname: '/profile' },
    label: 'Προφιλ',
    icon: appIcons.user_user,
    iconKey: 'user_user',
    accessibility: 'Προφιλ',
  },
] as const;
